[package]
name = "wayland-sys"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
libc = "0.2.170"
thiserror.workspace = true
static_assertions.workspace = true
va_list = "0.2.0"
