[package]
name = "unite-json"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
clap = { version = "4.5.36", features = ["derive"] }
serde = "1.0.219"
serde_json = "1.0.140"
tracing.workspace = true
