[workspace]
resolver = "3"
members = [
    "daemon",
    "extractor",
    "dxt",
    "transmute-extra",
    "wayland-scanner",
    "wayland",
    "wayland-sys",
]

[workspace.package]
version = "0.0.1"
edition = "2024"

[workspace.dependencies]
thiserror = "2.0.11"
safe-transmute = "0.11.3"
rayon = "1.10.0"
bitflags = "2.9.0"
wayland = { path = "wayland" }
waylnad-scanner = { path = "wayland-scanner" }
wayland-sys = { path = "wayland-sys" }
tracing = "0.1.41"
static_assertions = "1.1.0"
