[workspace]
resolver = "3"
members = [
    "crates/deploy-tool",
    "crates/dxt",
    "crates/extractor",
    "crates/project-parser",
    "crates/waywe-ipc",
    "crates/transmute-extra",
    "crates/unite-json",
    "crates/video",
    "crates/wayland-client",
    "crates/wayland-scanner",
    "crates/wayland-server",
    "crates/wayland-sys",
    "crates/waywe",
    "crates/waywe-daemon",
    "crates/waywe-ipc",
    "crates/waywe-runtime",
    "crates/waywe-scene",
    "crates/waywe-spirv-derive",
    "crates/waywe-shader-rs/shaderc-rs",
    "crates/waywe-shader-rs/shaderc-sys",
    "crates/waywe-rendering-api",
    "crates/waywe-scene-macros",
    "crates/examples/waywe-test-scene",
    "crates/examples/shadertoy-computer-were-made-for-cubes",
    "crates/daemonize/daemonize",
]

[workspace.package]
version = "0.0.15"
edition = "2024"
license = "MIT"
rust-version = "1.89"
authors = [
    "Varov Svyatoslav <slava-varov3@mail.ru>",
    "Alexander Filimonov <arnodarkrose@duck.com>",
]
repository = "https://www.github.com/hack3rmann/waywe-rs"

[workspace.dependencies]
wayland-client = { path = "crates/wayland-client", features = ["smallvec"] }
wayland-server = { path = "crates/wayland-server" }
wayland-sys = { path = "crates/wayland-sys" }
waywe-ipc = { path = "crates/waywe-ipc" }
waywe-runtime = { path = "crates/waywe-runtime" }
waywe-scene = { path = "crates/waywe-scene" }
waywe-spirv-derive = { path = "crates/waywe-spirv-derive" }
waywe-rendering-api = { path = "crates/waywe-rendering-api" }
waywe-scene-macros = { path = "crates/waywe-scene-macros" }
daemonize = { path = "crates/daemonize/daemonize" }
transmute-extra = { path = "crates/transmute-extra" }
video = { path = "crates/video" }
thiserror = "2.0.11"
safe-transmute = "0.11.3"
rayon = "1.10.0"
bitflags = "2.9.0"
tracing = "0.1.41"
static_assertions = "1.1.0"
tracing-test = "0.2.5"
paste = "1.0.15"
smallvec = { version = "1.14.0", features = ["union", "serde", "const_generics", "const_new", "write"] }
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
glam = { version = "0.30.3", features = ["bytemuck", "serde"] }
rustix = { version = "1.1.4", features = ["fs", "net", "process", "mm", "shm", "event", "pipe"] }
bytemuck = { version = "1.21.0", features = ["extern_crate_alloc", "derive"] }
libc = "0.2.170"
image = "0.25.6"
bincode = "2.0.1"
clap = { version = "4.5.40", features = ["derive"] }
tokio = { version = "1.43.0", features = ["full"] }
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.23"
fxhash = "0.2.1"
box_into_inner = "0.1.0"
futures-util = { version = "0.3.31", features = ["alloc"] }
abi_stable = "0.11.3"
bevy_ecs = "0.17.2"
ash = "0.38.0"
pollster = "0.4.0"
uuid = { version = "1.23.3", features = ["v7"] }
flate2 = "1.1.9"
tar = "0.4.46"
tap = "1.0.1"
miette = { version = "7.6.0", features = ["fancy"] }
display-error-chain = "0.2.2"
calloop = { version = "0.14.4", features = ["signals"] }
smallstr = { version = "0.3.1", features = ["union"] }
serde_dhall = "0.13.0"

[workspace.dependencies.wgpu]
git = "https://github.com/hack3rmann/wgpu.git"
rev = "a90a7a3107d6d9cf6ba7dd69445ea27594937b46"
version = "29.0.0"
features = ["glsl", "spirv"]
