[workspace]
resolver = "3"
members = [
    "daemon",
    "extractor",
    "dxt",
    "transmute-extra",
    "wayland-scanner",
    "wayland-client",
    "wayland-sys",
]

[workspace.package]
version = "0.0.1"
edition = "2024"

[workspace.dependencies]
wayland-client = { path = "wayland-client", features = ["smallvec"] }
waylnad-scanner = { path = "wayland-scanner" }
wayland-sys = { path = "wayland-sys" }
thiserror = "2.0.11"
safe-transmute = "0.11.3"
rayon = "1.10.0"
bitflags = "2.9.0"
tracing = "0.1.41"
static_assertions = "1.1.0"
tracing-test = "0.2.5"
paste = "1.0.15"
smallvec = { version = "1.14.0", features = ["union", "serde", "const_generics", "const_new"] }
tracing-subscriber = "0.3.19"
