[package]
name = "runtime"
version.workspace = true
edition.workspace = true

[dependencies]
rustix.workspace = true
thiserror.workspace = true
bincode = "2.0.1"
tracing.workspace = true
bytemuck.workspace = true
smallvec.workspace = true
