[package]
name = "runtime"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
rustix.workspace = true
thiserror.workspace = true
bincode.workspace = true
tracing.workspace = true
bytemuck.workspace = true
smallvec.workspace = true
libc.workspace = true
