[package]
name = "extractor"
version.workspace = true
edition.workspace = true

[dependencies]
safe-transmute.workspace = true
thiserror.workspace = true
bitflags.workspace = true
transmute-extra = {path = "../transmute-extra"}
