[package]
name = "deploy-tool"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cmd_lib = "1.9.6"
clap.workspace = true
tokio.workspace = true
lazy-regex = "3.4.1"
anyhow = "1.0.98"
