use super::ffi::{wl_proxy, wl_proxy_destroy};
use core::fmt;
use std::{marker::PhantomData, ptr::NonNull};

/// Represents a proxy object created on the libwayland backend
#[derive(PartialEq, Eq)]
pub struct WlProxy {
    pub(crate) raw: NonNull<wl_proxy>,
}

impl Drop for WlProxy {
    fn drop(&mut self) {
        unsafe { wl_proxy_destroy(self.raw.as_ptr()) }
    }
}

impl fmt::Debug for WlProxy {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct(std::any::type_name::<Self>())
            .finish_non_exhaustive()
    }
}

impl AsProxy for WlProxy {
    fn as_proxy(&self) -> WlProxyBorrow<'_> {
        unsafe { WlProxyBorrow::from_raw(self.raw) }
    }
}

/// The borrow of the proxy object
#[derive(Clone, Copy)]
pub struct WlProxyBorrow<'s> {
    pub raw: NonNull<wl_proxy>,
    pub _p: PhantomData<&'s WlProxy>,
}

impl WlProxyBorrow<'_> {
    /// Constructs [`WlProxyBorrow`] from raw pointer generated by libwayland backend
    ///
    /// # Safety
    ///
    /// - `value` should be valid [`wl_proxy`] pointer obtained from libwayland
    /// - no one has mutable access to the proxy object
    /// - the generated lifetime should be appropriate
    pub const unsafe fn from_raw(value: NonNull<wl_proxy>) -> Self {
        Self {
            raw: value,
            _p: PhantomData,
        }
    }

    /// Returns raw pointer to the libwayland backend
    pub const fn as_raw(self) -> NonNull<wl_proxy> {
        self.raw
    }
}

impl fmt::Debug for WlProxyBorrow<'_> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct(std::any::type_name::<Self>())
            .finish_non_exhaustive()
    }
}

impl AsProxy for WlProxyBorrow<'_> {
    fn as_proxy(&self) -> WlProxyBorrow<'_> {
        *self
    }
}

pub trait AsProxy {
    fn as_proxy(&self) -> WlProxyBorrow<'_>;
}
static_assertions::assert_obj_safe!(AsProxy);

// TODO(hack3rmann): missing docs
pub struct WlProxyQuery<T> {
    // TODO(hack3rmann): determine a nice API for object querying
    raw: *const wl_proxy,
    // TODO(hack3rmann): determine variance
    _p: PhantomData<fn() -> T>,
}

impl<T: AsProxy> WlProxyQuery<T> {
    pub const unsafe fn from_raw(raw: *const wl_proxy) -> Self {
        Self {
            raw,
            _p: PhantomData,
        }
    }

    pub const unsafe fn into_raw(self) -> *const wl_proxy {
        self.raw
    }
}

impl<T> Clone for WlProxyQuery<T> {
    fn clone(&self) -> Self {
        Self {
            raw: self.raw,
            _p: PhantomData,
        }
    }
}

impl<T> Copy for WlProxyQuery<T> {}

impl<T> fmt::Debug for WlProxyQuery<T> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct(std::any::type_name::<Self>())
            .finish_non_exhaustive()
    }
}

impl<T> PartialEq for WlProxyQuery<T> {
    fn eq(&self, other: &Self) -> bool {
        self.raw == other.raw
    }
}

#[derive(Clone, PartialEq, Copy)]
pub struct WlDynProxyQuery {
    // TODO(hack3rmann): determine a nice API for object querying
    raw: *const wl_proxy,
}

impl WlDynProxyQuery {
    pub const unsafe fn from_raw(raw: *const wl_proxy) -> Self {
        Self { raw }
    }
}

impl fmt::Debug for WlDynProxyQuery {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct(std::any::type_name::<Self>())
            .finish_non_exhaustive()
    }
}

macro_rules! define_proxies {
    ( $( $Proxy:ident ),* $(,)? ) => {
        $(
            pub struct $Proxy {
                pub(crate) proxy: WlProxy,
            }

            impl AsProxy for $Proxy {
                fn as_proxy(&self) -> WlProxyBorrow<'_> {
                    self.proxy.as_proxy()
                }
            }

            impl fmt::Debug for $Proxy {
                fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                    f.debug_struct(std::any::type_name::<Self>())
                        .finish_non_exhaustive()
                }
            }
        )*
    };
}

define_proxies! {
    WlRegistry, WlCompositor, WlRegion, WlSurface, WlOutput,
    WlShm, WlShmPool, ZwlrLayerShellV1, ZwlrLayerSurfaceV1,
}
